paths:
  notes: /Users/jyesselman2/Dropbox/notes
  dirs: /Users/jyesselman2/Dropbox/notes/dirs
  constructs: /Users/jyesselman2/Dropbox/notes/capture/construct
  sequencing-runs: /Users/jyesselman2/Dropbox/notes/capture/sequencing-runs
  sequencing-run-data: /Users/jyesselman2/Dropbox/data/sequencing_analysis
  